dist: xenial
sudo: false

language: python

python:
  - '3.6'
  - '3.7'
  - '3.8-dev'

install:
  - pip install -r requirements-dev.txt

script:
  - pytest -vl --cov=./

after_success:
  - codecov

notifications:
    email: false
