# ref: https://docs.travis-ci.com/user/languages/python
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"

script: nosetests

notifications:
    email: false
