# coding: utf-8

# flake8: noqa

"""
    RAWG Video Games Database API

     The largest open video games database.  ### Why build on RAWG - More than 350,000 games for 50 platforms including mobiles. - Rich metadata: tags, genres, developers, publishers, individual creators, official websites, release dates, Metacritic ratings. - Where to buy: links to digital distribution services - Similar games based on visual similarity. - Player activity data: Steam average playtime and RAWG player counts and ratings. - Actively developing and constantly getting better by user contribution and our algorithms.  ### Terms of Use - Free for personal use as long as you attribute RAWG as the source of the data and/or images and add an active hyperlink from every page where the data of RAWG is used. - Free for commercial use for startups and hobby projects with not more than 100,000 monthly active users or 500,000 page views per month. If your project is larger than that, email us at [api@rawg.io](mailto:api@rawg.io) for commercial terms. - No cloning. It would not be cool if you used our API to launch a clone of RAWG. We know it is not always easy to say what is a duplicate and what isn't. Drop us a line at [api@rawg.io](mailto:api@rawg.io) if you are in doubt, and we will talk it through. - You must include an API key with every request. The key can be obtained at https://rawg.io/apidocs. If you don’t provide it, we may ban your requests.  __[Read more](https://rawg.io/apidocs)__.   # noqa: E501

    The version of the OpenAPI document: v1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.2.0"

# import apis into sdk package
from rawg.api.creator_roles_api import CreatorRolesApi
from rawg.api.creators_api import CreatorsApi
from rawg.api.developers_api import DevelopersApi
from rawg.api.games_api import GamesApi
from rawg.api.genres_api import GenresApi
from rawg.api.platforms_api import PlatformsApi
from rawg.api.publishers_api import PublishersApi
from rawg.api.stores_api import StoresApi
from rawg.api.tags_api import TagsApi

# import ApiClient
from rawg.api_client import ApiClient
from rawg.configuration import Configuration
from rawg.exceptions import OpenApiException
from rawg.exceptions import ApiTypeError
from rawg.exceptions import ApiValueError
from rawg.exceptions import ApiKeyError
from rawg.exceptions import ApiAttributeError
from rawg.exceptions import ApiException
# import models into sdk package
from rawg.models.creator_roles_list200_response import CreatorRolesList200Response
from rawg.models.creators_list200_response import CreatorsList200Response
from rawg.models.developer import Developer
from rawg.models.developer_single import DeveloperSingle
from rawg.models.developers_list200_response import DevelopersList200Response
from rawg.models.game import Game
from rawg.models.game_esrb_rating import GameEsrbRating
from rawg.models.game_person_list import GamePersonList
from rawg.models.game_platform_metacritic import GamePlatformMetacritic
from rawg.models.game_platforms_inner import GamePlatformsInner
from rawg.models.game_platforms_inner_platform import GamePlatformsInnerPlatform
from rawg.models.game_platforms_inner_requirements import GamePlatformsInnerRequirements
from rawg.models.game_single import GameSingle
from rawg.models.game_store_full import GameStoreFull
from rawg.models.games_development_team_list200_response import GamesDevelopmentTeamList200Response
from rawg.models.games_list200_response import GamesList200Response
from rawg.models.games_screenshots_list200_response import GamesScreenshotsList200Response
from rawg.models.games_stores_list200_response import GamesStoresList200Response
from rawg.models.genre import Genre
from rawg.models.genre_single import GenreSingle
from rawg.models.genres_list200_response import GenresList200Response
from rawg.models.movie import Movie
from rawg.models.parent_achievement import ParentAchievement
from rawg.models.person import Person
from rawg.models.person_single import PersonSingle
from rawg.models.platform import Platform
from rawg.models.platform_parent_single import PlatformParentSingle
from rawg.models.platform_single import PlatformSingle
from rawg.models.platforms_list200_response import PlatformsList200Response
from rawg.models.platforms_lists_parents_list200_response import PlatformsListsParentsList200Response
from rawg.models.position import Position
from rawg.models.publisher import Publisher
from rawg.models.publisher_single import PublisherSingle
from rawg.models.publishers_list200_response import PublishersList200Response
from rawg.models.reddit import Reddit
from rawg.models.screen_shot import ScreenShot
from rawg.models.store import Store
from rawg.models.store_single import StoreSingle
from rawg.models.stores_list200_response import StoresList200Response
from rawg.models.tag import Tag
from rawg.models.tag_single import TagSingle
from rawg.models.tags_list200_response import TagsList200Response
from rawg.models.twitch import Twitch
from rawg.models.youtube import Youtube

